### ISSUE TITLE
account_id=`aws sts get-caller-identity|jq -r ".Account"`

### ISSUE THREAD

**Issue by Ichimikichiki** [aws-samples/aws-proton-sample-templates#11]
Did you mean
```
account_id=`aws sts get-caller-identity`|jq -r ".Account"
```
?

**Comment by clareliguori** [comment]
The original works for me in bash. Are you seeing different behavior?
```
account_id=`aws sts get-caller-identity|jq -r ".Account"`
echo $account_id
```

**Comment by paulsilver2000** [comment]
Hi @clareliguori  - The behaviour works okay if you have installed 'jq' on the machine. Having just spun up cloud9 - with no jq installed, it would be easier to have the command be : 
`aws sts get-caller-identity --query Account --text`
Which means i do not have to also install jq onto the cloud9 server.

**Comment by abhivr-amazon** [comment]
Replaced the command in README instructions. Closing the issue.
