### ISSUE TITLE
Error in Environment deployment

### ISSUE THREAD

**Issue by cmalcom** [aws-samples/aws-proton-sample-templates#15]
The beginning of this {%if ....%} statement is appended to the end of the line above.
It is preventing the table from being deployed.

https://github.com/aws-samples/aws-proton-sample-templates/blob/acbda0a74aab99f77755651bf63de99e402b6b42/lambda-crud-svc/environment/infrastructure/cloudformation.yaml#L27

**Comment by abhivr-amazon** [comment]
removed the if condition altogether as it was not required here.
