### ISSUE TITLE
Documentation minor issue when creating the private service

### ISSUE THREAD

**Issue by fdoa** [aws-samples/aws-proton-sample-templates#17]
https://github.com/aws-samples/aws-proton-sample-templates/tree/main/public-private-fargate-microservices

In the below snippet, need to rename from lb-private-fargate-svc to private-fargate-svc

`aws proton-preview create-service \
  --region us-east-2 \
  --service-name "back-end" \
  --repository-connection-arn arn:aws:codestar-connections:us-east-2:${account_id}:connection/<your-codestar-connection-id> \
  --repository-id "<your-source-repo-account>/<your-repository-name>" \
  --branch "main" \
  --template-major-version-id 1 \
  --service-template-arn arn:aws:proton:us-east-2:${account_id}:service-template/lb-private-fargate-svc \
  --spec file://specs/svc-private-spec.yaml`

**Comment by henrybravo** [comment]
thanks for commenting, this is fixed in: https://github.com/aws-samples/aws-proton-sample-templates/pull/18 @rafavallina

**Comment by rafavallina** [comment]
Closing as it is fixed
