### ISSUE TITLE
Error in Pipeline deployment

### ISSUE THREAD

**Issue by fv-yamaguchi** [aws-samples/aws-proton-sample-templates#20]
I guess wrong commit in 3d4224c1b76b390ee2c55857b07c8cfd91b469db.

I think the following is correct on line 74 of file public-private-fargate-microservices/service/loadbalanced-public-svc/pipeline/cloudformation.yaml.

`"aws proton-preview --endpoint-url https://proton.$AWS_DEFAULT_REGION.amazonaws.com --region $AWS_DEFAULT_REGION get-service --service-name $service_name | jq -r .service.spec > service.yaml",`

**Comment by hari-swrl** [comment]
hi @fv-yamaguchi , #36 
did you get the same kind of error
Thanks
