### ISSUE TITLE
use --query instead of jq

### ISSUE THREAD

**Issue by paulsilver2000** [aws-samples/aws-proton-sample-templates#24]
In the README.md there is a command you used : account_id=`aws sts get-caller-identity|jq -r ".Account"`

This means that you have to add jq into the machine which is not necessary, you can get the same result by using --query Account - 

account_id=`aws sts get-caller-identity --query Account --output text`

**Comment by abhivr-amazon** [comment]
Replaced the command in README instructions. Closing the issue.
