### ISSUE TITLE
Permissions for CodePipeline

### ISSUE THREAD

**Issue by Gamecock** [aws-samples/aws-proton-sample-templates#44]
When following the Proton Multi-Service Template, the last step fails because pipeline roles have not been configured.  Do the permissions need to be added to my User or the Proton role?  Which permissions are needed?

`$ aws proton create-service   --region us-west-2   --name "tasks-front-end"   --repository-connection-arn arn:aws:codestar-connections:us-west-2:${account_id}:connection/<your-codestar-connection-id>   --repository-id "<your-source-repo-account>/<your-repository-name>"   --branch "main"   --template-major-version 1   --template-name crud-api-service   --spec file://specs/svc-spec.yaml`

when credentials are filled in generates:
`An error occurred (ValidationException) when calling the CreateService operation: Operation cannot be run until pipeline roles have been configured`

**Comment by eranation** [comment]
Hi @Gamecock, I had the same issue and it got resolved when I went (in the Proton console UI) to settings, then Account roles and setup the roles there and no longer got the "Operation cannot be run until pipeline roles have been configured"

**Comment by Gamecock** [comment]
Closed by PR #46
