### ISSUE TITLE
Template Deployment Status stays Draft

### ISSUE THREAD

**Issue by Gamecock** [aws-samples/aws-proton-sample-templates#45]
When following the Proton Multi-Service Template, the template status shows DRAFT.

Wait for the environment template version to be successfully registered. You can try this command to see the registration status

aws proton get-environment-template-version \
  --region us-west-2 \
  --template-name "multi-svc-env" \
  --major-version "1" \
  --minor-version "0"

If the wait is ignored and you just proceed with the PUBLISH everything works.  The same happens on the service templates.  I've narrowed it down to one of 3 issues:

1) There is no need to wait-> If this is true I can submit a PR to remove those instructions.
2) There is a problem with the CLI, I am using `aws-cli/2.2.18 Python/3.8.8 Windows/10 exe/AMD64 prompt/off`
3) There is a problem with the API.

**Comment by augentry** [comment]
Since some templates take longer than others, the waiters provide an extra layer of safety to ensure you don't have issues. For that reason we added them to our instructions.

**Comment by rafavallina** [comment]
Closing this issue following @augentry's comment.
