### ISSUE TITLE
When attempting to deploy service  Deployment fails.

### ISSUE THREAD

**Issue by Gamecock** [aws-samples/aws-proton-sample-templates#47]
Following the lambda-multi-svc example 

the command
`aws proton get-service   --region us-west-2   --name "tasks-front-end"`

returns a failure
`
            "deploymentStatus": "FAILED",
            "deploymentStatusMessage": "[/Resources/FunctionBucket/Type/BucketEncryption/ServerSideEncryptionConfiguration/0/ServerSideEncryptionByDefault] 'null' values
are not allowed in templates",
`
            "deploymentStatus": "FAILED",
            "deploymentStatusMessage": "Service Instance(s): [arn:aws:proton:us-west-2:609826415497:service/tasks-front-end/service-instance/front-end] failed to deploy - canceling pipeline deployment",
`

I updated the svc-spec.yaml file to include a `code_uri` property becuase it was listed in the schema, but had no idea what value to give it.  That changed the failure message to:

`

**Comment by JiahuiTao** [comment]
Sorry for the issue. It was because of an indentation bug in the sample template. The fix has been merged: https://github.com/aws-samples/aws-proton-sample-templates/commit/406584441874c4a86b962f8fe93813d790454a24#diff-c53dd0a6f151cb35b2decc62544572cbd7f4f902c9711271fe7fa29d7b11bd31R11
