### ISSUE TITLE
fail to provision an environment in another account

### ISSUE THREAD

**Issue by zxkane** [aws-samples/aws-proton-sample-templates#58]
Following [the guide](https://github.com/aws-samples/aws-proton-sample-templates/tree/main/lambda-multi-svc#create-environment-in-one-account-and-provision-in-another-account) to create environment in one account and provision in another account, running below command to provision environment across account with error,

```
aws proton create-environment \
  --region us-west-2 \
  --name "multi-svc-beta" \
  --template-name multi-svc-env \
  --template-major-version 1 \
  --environment-account-connection-id ${environment_account_connection_id} \
  --spec file://specs/env-spec.yaml

An error occurred (ValidationException) when calling the CreateEnvironment operation: Idempotent parameter mismatch
```

Any idea how to resolve it?

**Comment by StevePotter** [comment]
@zxkane hey thanks for reaching out.  What happens when you call `aws proton get-environment --name multi-svc-env`?  It looks like there might already be an environment with that same name.

**Comment by zxkane** [comment]
Steve, thanks for giving the hint. I indeed created an environment with name `multe-svc-env` by following the [Create and Provisioning Environment in single account](https://github.com/aws-samples/aws-proton-sample-templates/tree/main/lambda-multi-svc#create-and-provision-environment-in-a-single-account). The error message of creating environment really is confused.

**Comment by StevePotter** [comment]
Yes, I can see how confusing that might be.  Would you expect something like "there is already an environment with these parameters"

**Comment by zxkane** [comment]
I would like to see an intuitive error message to point out the `name` of new environment  must be unique in the account and region combination. 

Also it would be helpful to improve the doc of `proton create-environment` API. Currently the doc of `name` parameter is simple.

```
aws proton create-environment help

…
       --name (string)
         The name of the environment.
…
```
