### ISSUE TITLE
Service template schema is not valid: Missing property [pipelineInputType]

### ISSUE THREAD

**Issue by relaxdiego** [aws-samples/aws-proton-sample-templates#9]
When running the following command:

```
aws proton-preview create-service-template-minor-version \
  --region us-west-2 \
  --template-name "lb-fargate-service" \
  --description "Version 1" \
  --major-version-id "1" \
  --source-s3-bucket proton-cli-templates-${account_id} \
  --source-s3-key svc-template.tar.gz
```

I get an error in the console saying that registration of the template failed due to `Missing property [pipelineInputType]`.

I've documented the steps that I've taken here: https://github.com/relaxdiego/aws-cf-ebs/tree/main/proton

**Comment by rafavallina** [comment]
Hi!  We tried to register your template and it worked for us! Let me ask (and I'm sorry if it's obvious) - can you double check that the .tar file that is in S3 has indeed the correct version of the schema and CFN template? In my own tests, that's the most typical mistake I make.

**Comment by relaxdiego** [comment]
Hi @rafavallina. Thanks for double checking. So I reviewed my script and lo and behold, I found the culprit:

```
if ! aws s3 ls --region ${region} s3://${s3_bucket}/${service_template_arch} >/dev/null; then
    aws s3 cp proton/${environment_template_arch} s3://${s3_bucket}/${service_template_arch} \
        --region ${region}
fi
```

Specifically that second line where it was copying the environment template archive rather than the service template archive. I'm going to close this issue now. Sorry for the false positive (negative??)

**Comment by rafavallina** [comment]
@relaxdiego Haha I was just coming to comment since we also found it at the same time. Good that it got resolved! Thanks for the interest, please keep sending feedback our way :)
